steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east4-docker.pkg.dev/granja-don-rafa-dev/curso-ms-nest/products-sms",
        "-f",
        "dockerfile.prod",p
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east4-docker.pkg.dev/granja-don-rafa-dev/curso-ms-nest/products-sms",
      ]